name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: flake8
      uses: py-actions/flake8@v2
    - name: black
      uses: psf/black@stable
      with:
        options: "--check --diff -l 90"

  build_wheels:
    name: Build wheel on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.7.0
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl